general_cfg:
  algo_name: DQN
  device: cuda
  env_name: MiniGrid-Empty-16x16-v0
  env_render: rgb_array
  mode: train
  load_checkpoint: false
  load_path: None
  max_steps: 200
  seed: 1
  save_fig: true
  show_fig: false
  test_eps: 10
  train_eps: 10000
  eval_per_episode: 5
  eval_eps: 10
algo_cfg:
  batch_size: 64
  buffer_size: 10000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.98
  lr: 0.0001
  target_update: 10